### ISSUE TITLE
copyright

### ISSUE THREAD

**Issue by jsun1590** [wacedungeoner/wace#5]
i am thinking there might be potentially, perhaps, some minor copyright concerns with this repo (repository).

**Comment by wacedungeoner** [comment]
Hey there,
I'm not sure if the test papers here are copyrighted, everything in this repository was sourced from the Discord server, so you'd have to ask the people who've uploaded resources there or linked to other Google Drives.
Every commit here is titled with a description of where the resources came from, usually they are from server members' Google Drives.
This repository is merely a collection of everything that has been uploaded to the server, in a central location.
Hopefully that helps.

**Comment by jsun1590** [comment]
That helped a lot. Thanks.
